### ISSUE TITLE
iOS Light Mode: Sheet With Dark Background Shows Glitchy Border, Feature or bug :D ?

### ISSUE THREAD

**Issue by smidlma** [lodev09/react-native-true-sheet#212]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

Hard to see from video but very visible on real device, look at the top corners, but it goes all over the sheet border.

https://github.com/user-attachments/assets/e7964fbb-0fc2-4ed2-a0d1-08c7a26bcc16

### Library version

^2.0.6

### Environment info

System:
  OS: macOS 26.1
  CPU: (12) arm64 Apple M4 Pro
  Memory: 951.13 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.14.0
    path: /Users/smidlma/.nvm/versions/node/v22.14.0/bin/node
  Yarn:
    version: 1.22.22
    path: /Users/smidlma/.nvm/versions/node/v22.14.0/bin/yarn
  npm:
    version: 11.6.2
    path: /Users/smidlma/.nvm/versions/node/v22.14.0/bin/npm
  Watchman:
    version: 2025.02.17.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 25.0
      - iOS 26.0
      - macOS 26.0
      - tvOS 26.0
      - visionOS 26.0
      - watchOS 26.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23726.103.2422.13103373
  Xcode:
    version: 26.0.1/17A400
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 20.0.2
    wanted: ^20.0.2
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.81.5
    wanted: 0.81.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

```jsx
    <TrueSheet
      ref={sheet}
      backgroundColor={THEME.dark.background} // 'hsl(231 50% 8%)',
      name={NOTIFICATIONS_SHEET_NAME}
      // @ts-expect-error Typing is not correct
      scrollRef={scrollview}
      sizes={[`${NOTIFICATIONS_FIRST_SNAP_POINT}%`, `${NOTIFICATION_LAST_SNAP_POINT}%`]}
    >
      <NotificationsContainer scrollRef={scrollview} />
    </TrueSheet>```

### Reproducible example repository

https://none

**Comment by lodev09** [comment]
Fixed in #214

**Comment by matyasproch** [comment]
@lodev09 Hi, we are still experiencing this issue in the latest version 3.9.9. Light theme + dark background of the sheet results in this glitchy white border on iOS

**Comment by matyasproch** [comment]
What is weird that for me it's happening only in the version downloaded from TestFlight, in local development it doesnt occur
