### ISSUE TITLE
detents={["auto"]} issue on Android

### ISSUE THREAD

**Issue by doguyilmaz** [lodev09/react-native-true-sheet#274]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### When using on android detents={['auto']} it does not respect, opens to full size.

Example Code:
 ```tsx
<SafeAreaView style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
  <Button title="Open TrueSheet" onPress={() => sheet.current?.present()} />
  <TrueSheet ref={sheet} detents={['auto']}>
    <View style={{ padding: 20, height: 150, backgroundColor: 'lightgray' }}>
      <Text>Example Content</Text>
    </View>
  </TrueSheet>
</SafeAreaView>
```

Result:

https://github.com/user-attachments/assets/a6dfc80e-bba3-4d50-9ee0-a9ad5ce41d3e

## 

###  In another case, if i set "detents={['auto', 1]}" and now it opens correct size respecting auto but now we got 3 state/detents even though we have 2 (auto and 1).

Example Code:
```tsx
  <SafeAreaView style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    <Button title="Open TrueSheet" onPress={() => sheet.current?.present()} />
    <Button title="Open TrueSheet:1" onPress={() => sheet.current?.present(1)} />
    <TrueSheet ref={sheet} detents={['auto', 1]}>
      <View style={{ padding: 20, height: 150, backgroundColor: 'lightgray' }}>
        <Text>Example Content</Text>
      </View>
    </TrueSheet>
  </SafeAreaView>
```

Result: (mid state/position not expected)

https://github.com/user-attachments/assets/10eed944-584f-430a-9daf-955553998076

### Library version

3.1.0-beta.3

### Environment info

```shell
"expo": "~53.0.24",
"react": "19.0.0",
"react-native": "0.79.6",
"react-native-safe-area-context": "^5.4.0",
"react-native-screens": "~4.11.1"

newArchEnabled: true

Android: 16 & API 36
Emulator: Pixel 9 Pro
```

### Steps to reproduce

1. Install latest @lodev09/react-native-true-sheet@3.1.0-beta.3
2. Use example codes
3. For the first example/issue: just present the sheet it opens to full (not expected)
4. For the second example/issue: present and just drag to up and/or present(1) and drag down the sheet and it somehow catches the not existed middle detent

### Reproducible example repository

https://github.com/lodev09/react-native-true-sheet/issues/274

**Comment by lodev09** [comment]
@doguyilmaz thanks! should be fixed now

**Comment by lxup** [comment]
Hi,
I tested 3.1.0-beta.4 and the auto detent fix works for simple static content, but I still have a remaining issue on Android when using scrollable.
I made a full repro here:
https://github.com/lxup/react-native-true-sheet-scrollable-bug

Here are the four cases from the repo:

1. `scrollable` + scrollview (FlatList)
```tsx
<TrueSheet detents={['auto']} scrollable>
  <FlatList ... />
</TrueSheet>
```
-> always opens full-size (auto ignored)

2. scrollview without `scrollable`
```tsx
<TrueSheet detents={['auto']}>
  <FlatList ... />
</TrueSheet>
```
-> opens at correct auto height
-> but the list is no longer scrollable on Android

3. `scrollable` + static content
```tsx
<TrueSheet detents={['auto']} scrollable>
  <View ... />
</TrueSheet>
```
-> still opens full-size (auto ignored)

4. static content without `scrollable`
```tsx
<TrueSheet detents={['auto']}>
  <View ... />
</TrueSheet>
```
-> works correctly (auto height)

This behavior only happens on Android.
On iOS, all cases behave as expected.

If this is the expected behavior when using scrollable, what’s the recommended way to keep auto detent sizing on Android?
Happy to open a new issue if needed.

**Comment by lodev09** [comment]
Unfortunately, `auto` does not work very well on android scrollable. Don't use it 😅
I've done so many trial errors to support it but it's a limitation on Android + RN. I've documented it here:
https://sheet.lodev09.com/guides/scrolling/#android

**Comment by lodev09** [comment]
The main issue is mentioned here: https://sheet.lodev09.com/troubleshooting#unable-to-drag-on-android
It's due to RN's scrollview implementation that's causing conflict with the sheet's gesture. If scrollview content is smaller or equal to the sheet's height, gesture doesn't work, thus `auto` not working.
